name = "ConjugateGradientsGPU"
uuid = "0cf172c8-095c-46f4-9dd2-d60831738d9b"
authors = ["Arpit Babbar <arpitbabbar@gmail.com>"]
version = "0.1.0"

[deps]
GPUArraysCore = "46192b85-c4d5-4398-a991-12ede77f4527"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.0"
